name: Deploy to VPS (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: nitip-prod

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build New Docker Image
        run: |
          docker compose build app

      - name: Restart Container
        run: |
          docker compose up -d

      - name: Cleanup Old Images
        run: |
          docker image prune -f